<?php if ($this->isActive()): /* ?>

<script type="text/javascript">
    var upsParams = upsParams || [];
    upsParams.push(['customer', '<?php echo $this->getCustomer(); ?>']);
    var upsScript = document.createElement('script');
    upsScript.setAttribute('type','text/javascript');
    upsScript.setAttribute('src', '//rec.quartic.pl/qon.js');
    upsScript.setAttribute('async','async');
    var upsAnchor = document.getElementsByTagName('script')[0];
    upsAnchor.parentNode.insertBefore(upsScript, upsAnchor);
    function quartic_rec (recommendations, slot) {
        var parameters = { slot: slot };
        var i;
        var count = recommendations.length;
        for (var i = 0; i < count; i++) {
            parameters['sku[' + i + ']'] = recommendations[i][0];
            parameters['url[' + i + ']'] = recommendations[i][1];
        }
        new Ajax.Request('<?php echo Mage::getUrl('quartic/frame/index'); ?>', {
            method: 'post',
            parameters: parameters,
            onSuccess: function(transport) {
                $(slot).update(transport.responseText);
            }
        });
    }
</script>
*/ ?>
<script type="text/javascript">
    function _qAddEvent(element, eventName, fn) {
        if (element.addEventListener) {
            element.addEventListener(eventName, fn, false);
        } else if (element.attachEvent) {
            if (eventName == 'DOMContentLoaded') {
                eventName = 'readystatechange';
                fn = function() {
                    if ( document.readyState === "complete" ) {
                        fn();
                    }
                };
            }
            element.attachEvent('on' + eventName, fn);
        }
    }
    _qAddEvent(window, 'DOMContentLoaded', function() {
        var _qprods = '';
        if (typeof _qCartProducts != 'undefined') {
            _qprods = _qCartProducts();
        }
        xhr = new XMLHttpRequest();
        xhr.open('POST', 'https://shopapi.quarticon.com/pluginMagento/content');
        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        xhr.onload = function() {
            window.upsParams = window.upsParams || [];
            upsParams.push(['user', '<?php echo $this->getUser(); ?>']);
            if (xhr.readyState != 4 || xhr.status != 200) return;
            if (typeof _qViewScript != 'undefined') {
                _qViewScript();
            }
            if (typeof _qTransactionScript != 'undefined') {
                _qTransactionScript();
            }
            eval(xhr.responseText);
        };
        var _qparams = 'storeName='+encodeURIComponent('<?php echo $this->getStoreName(); ?>')+'&template=footer';
        _qparams += '&products='+encodeURIComponent(_qprods);
        xhr.send(_qparams);
    });
</script>
<?php endif; ?>