<?php if ($this->isActive()): ?>
<div id="slt_cart"></div>
<script type="text/javascript">
    var upsParams = upsParams || [];
    upsParams.push(['action','recommend']);
    upsParams.push(['tag_id','quartic_cart']);
    upsParams.push(['customer', '<?php echo $this->getCustomer(); ?>']);
    upsParams.push(['slot', 'slt_cart']);
    upsParams.push(['user', '<?php echo $this->getUser(); ?>']);
    upsParams.push(['products', '<?php echo $this->getProducts(); ?>']);
    upsParams.push(['execute']);
</script>
<?php endif; ?>